spring:
  application:
    name: "Novy"
  datasource:
    url: "jdbc:postgresql://localhost:5432/roadmaper"
    username: "postgres"
    password: "?"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: "Alan"
      password: "1101"
server:
  port: 8080
